### ISSUE TITLE
MongoPlugin non compila con VS2022

### ISSUE THREAD

**Issue by crisim** [Arxivar/SamplePlugins#19]
se installato Visual Studio 2022 MongoPlugin non compila

prima di tutto va in errore "npm install" a causa di "node-sass" versione 6.0.1 che non trova visual studio
cambiando la versione in 8.0.0 "npm install" va a buon fine.

compilando poi la soluzione poi esce il seguente errore

`1>------ Inizio compilazione: Progetto: MongoPlugin, Configurazione: Debug Any CPU ------
1>"Building webpack"
1>
1>> webpack-demo@1.0.0 build
1>> webpack --config webpack.config.js --progress
1>
1><s> [webpack.Progress] 0% compiling
1><s> [webpack.Progress] 10% building 0/0 modules 0 active
1><s> [webpack.Progress] 10% building 0/1 modules 1 active D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\node_modules\babel-loader\lib\index.js??ref--4-0!D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\scripts\src\MongoPlugin.ts
1>node:internal/crypto/hash:71
1>  this[kHandle] = new _Hash(algorithm, xofLen);
1>                  ^
1>
1>Error : error : 0308010C:digital envelope routines::unsupported
1>    at new Hash (node:internal/crypto/hash:71:19)
1>    at Object.createHash (node:crypto:133:10)
1>    at module.exports (D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\node_modules\webpack\lib\util\createHash.js:135:53)
1>    at NormalModule._initBuildHash (D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\node_modules\webpack\lib\NormalModule.js:417:16)
1>    at handleParseError (D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\node_modules\webpack\lib\NormalModule.js:471:10)
1>    at D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\node_modules\webpack\lib\NormalModule.js:503:5
1>    at D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\node_modules\webpack\lib\NormalModule.js:358:12
1>    at D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\node_modules\loader-runner\lib\LoaderRunner.js:373:3
1>    at iterateNormalLoaders (D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
1>    at iterateNormalLoaders (D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
1>    at D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\node_modules\loader-runner\lib\LoaderRunner.js:236:3
1>    at context.callback (D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
1>    at D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\node_modules\babel-loader\lib\index.js:44:71 {
1>  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
1>  library: 'digital envelope routines',
1>  reason: 'unsupported',
1>  code: 'ERR_OSSL_EVP_UNSUPPORTED'
1>}
1>
1>Node.js v18.12.1
1>D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\MongoPlugin\MongoPlugin.csproj(23,5): error MSB3073: uscita dal comando "call "D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\\prebuild.bat" "D:\deve\SamplePlugins\LinkWorkflowV2\MongoPlugin\MongoPlugin\bin\Debug\netstandard2.1\"" con codice 1.
1>Compilazione progetto "MongoPlugin.csproj" NON COMPLETATA.`
[log.txt](https://github.com/Arxivar/SamplePlugins/files/10805774/log.txt)

**Comment by crisim** [comment]
ok, sembra che aggiornando webpack e webpack-cli si riesca a compilare.
